### ISSUE TITLE
Please can you update for Endwalker 6.0 version ?

### ISSUE THREAD

**Issue by inanmb** [Caraxi/FPSPlugin#4]
Thank you <3

**Comment by unixtreme** [comment]
It looks like the memory offset has to be changed, no idea about FFXIV modding to look into it myself.

**Comment by Caraxi** [comment]
I'll get it updated. sorry for delay

**Comment by doomsz** [comment]
> I'll get it updated. sorry for delay

thankss

**Comment by Aida-Enna** [comment]
poke

**Comment by Zaphod392** [comment]
One of my favorite plugins! :) An update would definitely be appreciated by many!

**Comment by doomsz** [comment]
waiting on this one aswell

**Comment by xPumaa** [comment]
@Caraxi I found out that the address offset is 0x17C4 instead of 0x165C. Hope that helps :)

**Comment by doomsz** [comment]
> I'll get it updated. sorry for delay

any news ?
