### ISSUE TITLE
Double overlay issue

### ISSUE THREAD

**Issue by Xorag** [Caraxi/FPSPlugin#7]
Hello! I've noticed recently, within the last few days a 00:0X overlay appearing behind the FPS counter, like so:

![Screenshot 2022-01-17 002316](https://user-images.githubusercontent.com/42698965/149719527-1a51ca03-7b03-4200-94ef-6406f6dca5c9.png)

I'm on the latest version playing on the windows/steam client. If I can provide any other info please let me know. Thanks!

**Comment by Caraxi** [comment]
Disable or move whatever is adding that 00:0X overlay then

**Comment by Xorag** [comment]
Sorry, it was the engage timer addon that happened to put this in the exact same spot, and I didn't realize the feature was a thing.
